import pygame
TILESIZE   = 32
PLAYERSIZE = [32, 32]
SPRITESIZE = 32

ROOM_DIM  = (16,9)
WORLD_DIM = (5,5)

WIDTH, HEIGHT = ROOM_DIM[0] * TILESIZE, ROOM_DIM[1] * TILESIZE
SCALE = 3

MOVEDELAY = 0.1
ROOM_DIM = (16,9)
ROOM_COUNT = 25

TIMER_ZERO = pygame.USEREVENT + 1
